export const blogList = [
    {
        id: 1,
        title: 'HTML. 1 урок',
        category: 'HTML',
        subCategory: ['frontend', 'основы', 'введение'],
        description:
            "HTML расшифровывается как Hyper Text Markup Language, т.е. язык гипертекстовой разметки — основной строительный блок веб-страниц, используется для создания и визуального представления веб-станиц.",
        cover: '/images/designer-1.jpg',
        theory1: 'теория'  ,
        example1: 'пример' ,
        theory2: 'теория',
        example2: 'пример',
        theory3: 'теория',
        task: 'задание',
    },
    {
        id: 2,
        title: 'HTML. 2 урок',
        category: 'HTML',
        subCategory: ['vacation', 'holidays', 'sight seeing'],
        description:
            "В языке HTML всё, что вы напишите в HTML-документе, будет выведено на экран браузера сплошным текстом, то есть браузер игнорирует переводы строк, а также несколько набранных вами подряд пробелов заменяются одним. Теги — это управляющие команды, которые были придуманы для того, чтобы отформатировать текст, т.е. теги говорят браузеру о том, как именно нужно вывести на экран часть текста, заключенную в теги. Для создания тега между угловыми скобками вводится HTML-код, который предназначен только для браузеров. Посетители сайта не видят теги. Как уже отмечалось выше, все теги начинаются с угловой скобки < и заканчиваются угловой скобкой > . После открывающей угловой скобки следует имя тега (команды).   Например, тег <em> предназначен для акцентирования текста, браузеры отображают такой текст курсивным начертанием. Когда браузер обнаруживает этот тег, он переключается на форматирование курсивным шрифтом текста, следующего за тегом..",
        authorName: 'John Doe',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/images/f67396fc3cfce63a28e07ebb35d974ac.jpg',
    },
    {
        id: 3,
        title: 'HTML. 3 урок',
        category: 'HTML',
        subCategory: ['e-commerce store', 'clothing', 'shopping store'],
        description:
            "Элемент — это основа языка HTML. Он является основой построения сайта и может описывать документ в целом или способ форматирования текста. Все, что вы захотите создать на вашей веб-странице, будет сделано с помощью элементов. HTML обеспечивает структуру документа, состоящего из всех отдельных HTML-элементов на странице.HTML также обеспечивает семантику HTML документа. Элементы, как правило, используются для конкретного назначения. Например, уровень заголовка <h1> является более важным, чем уровень <h2>.Элементы включают в себя всё, что находится между парными тегами элемента, включая сами теги. Например, элемент <p> обозначает параграф; элемент <img> обозначает изображение..",
        authorName: 'John Doe',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/images/fQwuyKJ9qxjSbr6REcgtmW-1200-80.jpg',
    },
    {
        id: 4,
        title: 'CSS. 1 урок',
        category: 'CSS',
        subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'John Doe',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/images/graphic-design-trends.png',
    },
    {
        id: 5,
        title: 'CSS. 2 урок',
        category: 'CSS',
        subCategory: ['bbq', 'food', 'lifestyle'],
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'John Doe',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/images/make-it-personal.jpg',
    },
    {
        id: 6,
        title: 'CSS. 3 урок',
        category: 'CSS',
        subCategory: ['beaches', 'sea', 'holidays'],
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'John Doe',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover:
            '/images/Purple-Combination-colors-graphic-design-predictions-1024x576-1024x576.jpg',
    },
    {
        id: 7,
        title: 'JS. 1 урок',
        category: 'JS',
        subCategory: ['skill', 'design', 'passion'],
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'John Doe',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/images/Synthwave-Postmodern.jpg',
    },
];